export const NAMES = {
  ACTIONS: {
    edit: 'edit',
    create: 'create',
    delete: 'delete',
    list: 'list',
    view: 'view',
  },
  BASIC_PAGES: {
    empty: '',
    id: 'id',
    home: 'home',
    about: 'about',
    login: 'login',
    logout: 'logout',
    settings: 'settings',
    register: 'register',
    forgotPassword: 'forgot-password',
    resetPassword: 'reset-password',
    profile: 'profile',
    admin: 'admin',
    account: 'account',
    session: 'session',
  },
  DOMAIN_PAGES: {
    starwars: 'starwars',
    person: 'person',
    people: 'people',
    film: 'film',
  },
};
