/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface IssueToken { 
    accountId: string;
    securityCode: string;
    recoveryExpiration: Date;
    type: IssueToken.TypeEnum;
    status: IssueToken.StatusEnum;
    createdAt?: Date;
    lastModified?: Date;
    id?: string;
}
export namespace IssueToken {
    export type TypeEnum = 'ACCOUNT_ACTIVATION' | 'FORGOT_PASSWORD' | 'TEMPORARY_PASSWORD';
    export const TypeEnum = {
        ACCOUNTACTIVATION: 'ACCOUNT_ACTIVATION' as TypeEnum,
        FORGOTPASSWORD: 'FORGOT_PASSWORD' as TypeEnum,
        TEMPORARYPASSWORD: 'TEMPORARY_PASSWORD' as TypeEnum
    };
    export type StatusEnum = 'OPEN' | 'CLOSED';
    export const StatusEnum = {
        OPEN: 'OPEN' as StatusEnum,
        CLOSED: 'CLOSED' as StatusEnum
    };
}