/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RoleDto { 
    role: RoleDto.RoleEnum;
}
export namespace RoleDto {
    export type RoleEnum = 'USER' | 'ADMIN' | 'MANAGER';
    export const RoleEnum = {
        USER: 'USER' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum,
        MANAGER: 'MANAGER' as RoleEnum
    };
}